certificateRequests:
  paths:
    - example/tls/requests/ca
    - example/tls/requests/client
    - example/tls/requests/server
default:
  countries: FR
  provinces: France
  organizations: uCerts
  localities: Bordeaux
