log:
  level: debug
  format: text
  timestamp:
    enable: true
    format: 2006-01-02T15:04:05
certificateRequests:
  paths:
    - example/tls/requests/ca
    - example/tls/requests/client
    - example/tls/requests/server
default:
  countries: FR
  provinces: France
  organizations: uCerts
  localities: Bordeaux
