certificateRequests:
  paths:
    - example/tls/requests/client
    - example/tls/requests/server
caPath: example/tls/requests/ca.crt
caKeyPath: example/tls/requests/ca.key
default:
  countries: FR
  provinces: France
  organizations: uCerts
  localities: Bordeaux
