tls:
  configPaths:
    - example/tls/config/client
    - example/tls/config/server
caPath: example/tls/config/ca.crt
caKeyPath: example/tls/config/ca.key
default:
  countries: FR
  provinces: France
  organizations: uCerts
  localities: Bordeaux
